package ru.porabote.springbootrestauth.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import ru.porabote.springbootrestauth.components.FilesComponent;
import ru.porabote.springbootrestauth.model.FileModel;
import ru.porabote.springbootrestauth.repository.FileRepository;

import java.io.File;
import java.io.IOException;
import java.util.Map;

@Controller
public class FilesController {

    static String UPLOAD_PATH;

    public FilesController() throws IOException {
        this.UPLOAD_PATH = new File(".").getCanonicalPath() + "/src/main/storage/uploaded/";
    }

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FileRepository fileRepository;

    @PostMapping(path="/file")
    public @ResponseBody String addFile (@RequestParam String filename, @RequestParam MultipartFile file) throws IOException {

        String dirPath = this.UPLOAD_PATH;
        FilesComponent.makeDirectory(dirPath);
        FilesComponent.makeFile(dirPath + filename);

        File fileTmp = new File(dirPath + filename);
        fileTmp.createNewFile();

        file.transferTo(fileTmp);

        FileModel f = new FileModel();
        f.setFilename(filename);
        f.setSize(fileTmp.length());
        fileRepository.save(f);
        return "Saved";
    }

    @DeleteMapping(path="/file")
    public @ResponseBody String deleteFile (@RequestParam String filename) throws IOException {

        String dirPath = this.UPLOAD_PATH;
        fileRepository.deleteByFilename(filename);
        return "Deleted";
    }

    @GetMapping(path="/file")
    public @ResponseBody FileModel download(@RequestParam String filename) {
        return fileRepository.findFirstByFilename(filename);
    }

    @PutMapping(path="/file")
    public @ResponseBody String edit(@RequestBody Map<String, String> payload, @RequestParam(name="filename") String oldName) {

        String newName = payload.get("filename");

        FileModel record = fileRepository.findFirstByFilename(oldName);
        record.setFilename(newName);
        fileRepository.save(record);

        return this.UPLOAD_PATH;
    }

    @GetMapping(path="/list")
    public @ResponseBody Iterable<FileModel> getAllUsers() {
        return fileRepository.findAll();
    }
}